/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.tables.daos;


import com.hiddenswitch.framework.schema.tables.ClientDefaultRoles;
import com.hiddenswitch.framework.schema.tables.records.ClientDefaultRolesRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.util.Collection;

import org.jooq.Configuration;
import org.jooq.Record2;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientDefaultRolesDao extends AbstractReactiveVertxDAO<ClientDefaultRolesRecord, com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles, Record2<String, String>, Future<List<com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles>>, Future<com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles>, Future<Integer>, Future<Record2<String, String>>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<ClientDefaultRolesRecord,com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles,Record2<String, String>> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public ClientDefaultRolesDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
        super(ClientDefaultRoles.CLIENT_DEFAULT_ROLES, com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles.class, new ReactiveClassicQueryExecutor<ClientDefaultRolesRecord,com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles,Record2<String, String>>(configuration,delegate,com.hiddenswitch.framework.schema.tables.mappers.RowMappers.getClientDefaultRolesMapper()));
    }

    @Override
    protected Record2<String, String> getId(com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles object) {
        return compositeKeyRecord(object.getClientId(), object.getRoleId());
    }

    /**
     * Find records that have <code>role_id IN (values)</code> asynchronously
     */
    public Future<List<com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles>> findManyByRoleId(Collection<String> values) {
        return findManyByCondition(ClientDefaultRoles.CLIENT_DEFAULT_ROLES.ROLE_ID.in(values));
    }

    /**
     * Find records that have <code>role_id IN (values)</code> asynchronously limited by the given limit
     */
    public Future<List<com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles>> findManyByRoleId(Collection<String> values, int limit) {
        return findManyByCondition(ClientDefaultRoles.CLIENT_DEFAULT_ROLES.ROLE_ID.in(values),limit);
    }

    @Override
    public ReactiveClassicQueryExecutor<ClientDefaultRolesRecord,com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles,Record2<String, String>> queryExecutor(){
        return (ReactiveClassicQueryExecutor<ClientDefaultRolesRecord,com.hiddenswitch.framework.schema.tables.pojos.ClientDefaultRoles,Record2<String, String>>) super.queryExecutor();
    }
}
