package net.demilich.metastone.game.behaviour.heuristic;

/**
 * The coefficients in a linear combination of features used by {@link ThreatBasedHeuristic} to calculate a score for a
 * game state.
 */
public enum WeightedFeature {
	RED_MODIFIER,
	YELLOW_MODIFIER,
	OWN_HP_FACTOR,
	OPPONENT_HP_FACTOR,
	OWN_CARD_COUNT,
	OPPONENT_CARD_COUNT,
	MINION_INTRINSIC_VALUE,
	MINION_ATTACK_FACTOR,
	MINION_HP_FACTOR,
	MINION_RED_TAUNT_MODIFIER,
	MINION_YELLOW_TAUNT_MODIFIER,
	MINION_DEFAULT_TAUNT_MODIFIER,
	MINION_WINDFURY_MODIFIER,
	MINION_DIVINE_SHIELD_MODIFIER,
	MINION_SPELL_POWER_MODIFIER,
	MINION_STEALTHED_MODIFIER,
	MINION_UNTARGETABLE_BY_SPELLS_MODIFIER,
	CURSED_FACTOR,
	HARD_REMOVAL_VALUE,
	QUEST_COUNTER_VALUE,
	EMPTY_MANA_CRYSTAL_VALUE,
	OPPOSING_EMPTY_MANA_CRYSTAL_VALUE,
	QUEST_REWARD_VALUE,
	OWN_ROASTED_VALUE,
	OPPONENT_ROASTED_VALUE
}
