package com.hiddenswitch.framework.graphql;

public enum GameEventType {

    ALL("ALL"),
    AFTER_PHYSICAL_ATTACK("AFTER_PHYSICAL_ATTACK"),
    AFTER_PLAY_CARD("AFTER_PLAY_CARD"),
    AFTER_SPELL_CASTED("AFTER_SPELL_CASTED"),
    AFTER_SUMMON("AFTER_SUMMON"),
    ATTRIBUTE_APPLIED("ATTRIBUTE_APPLIED"),
    ARMOR_GAINED("ARMOR_GAINED"),
    BEFORE_PHYSICAL_ATTACK("BEFORE_PHYSICAL_ATTACK"),
    BEFORE_SUMMON("BEFORE_SUMMON"),
    BOARD_CHANGED("BOARD_CHANGED"),
    CARD_ADDED_TO_DECK("CARD_ADDED_TO_DECK"),
    CARD_SHUFFLED("CARD_SHUFFLED"),
    DAMAGE("DAMAGE"),
    DECAY("DECAY"),
    DID_END_SEQUENCE("DID_END_SEQUENCE"),
    DISCARD("DISCARD"),
    DISCOVER("DISCOVER"),
    DRAIN("DRAIN"),
    DRAW_CARD("DRAW_CARD"),
    ENRAGE_CHANGED("ENRAGE_CHANGED"),
    ENTITY_TOUCHED("ENTITY_TOUCHED"),
    ENTITY_UNTOUCHED("ENTITY_UNTOUCHED"),
    EXCESS_HEAL("EXCESS_HEAL"),
    FATIGUE("FATIGUE"),
    GAME_START("GAME_START"),
    HEAL("HEAL"),
    HERO_POWER_USED("HERO_POWER_USED"),
    INVOKED("INVOKED"),
    JOUST("JOUST"),
    KILL("KILL"),
    LOSE_DIVINE_SHIELD("LOSE_DIVINE_SHIELD"),
    LOSE_DEFLECT("LOSE_DEFLECT"),
    LOSE_STEALTH("LOSE_STEALTH"),
    MAX_HP_INCREASED("MAX_HP_INCREASED"),
    MAX_MANA("MAX_MANA"),
    MANA_MODIFIED("MANA_MODIFIED"),
    MISSILE_FIRED("MISSILE_FIRED"),
    OVERLOAD("OVERLOAD"),
    PERFORMED_GAME_ACTION("PERFORMED_GAME_ACTION"),
    PHYSICAL_ATTACK("PHYSICAL_ATTACK"),
    PLAY_CARD("PLAY_CARD"),
    PRE_DAMAGE("PRE_DAMAGE"),
    PRE_GAME_START("PRE_GAME_START"),
    QUEST_PLAYED("QUEST_PLAYED"),
    QUEST_SUCCESSFUL("QUEST_SUCCESSFUL"),
    RETURNED_TO_HAND("RETURNED_TO_HAND"),
    ROASTED("ROASTED"),
    REVEAL_CARD("REVEAL_CARD"),
    SECRET_PLAYED("SECRET_PLAYED"),
    SECRET_REVEALED("SECRET_REVEALED"),
    SPELL_CASTED("SPELL_CASTED"),
    SUMMON("SUMMON"),
    TARGET_ACQUISITION("TARGET_ACQUISITION"),
    TRIGGER_FIRED("TRIGGER_FIRED"),
    TURN_END("TURN_END"),
    TURN_START("TURN_START"),
    SILENCE("SILENCE"),
    WEAPON_DESTROYED("WEAPON_DESTROYED"),
    WEAPON_EQUIPPED("WEAPON_EQUIPPED"),
    WILL_END_SEQUENCE("WILL_END_SEQUENCE"),
    DESTROY_WILL_QUEUE("DESTROY_WILL_QUEUE"),
    TAP_ACTIVATED("TAP_ACTIVATED"),
    HONORABLE_KILL("HONORABLE_KILL"),
    ROGUE_CHOICE("ROGUE_CHOICE"),
    GAME_INITIALIZED("GAME_INITIALIZED");

    private final String graphqlName;

    private GameEventType(String graphqlName) {
        this.graphqlName = graphqlName;
    }

    @Override
    public String toString() {
        return this.graphqlName;
    }

}
