package com.hiddenswitch.framework.graphql;

/**
 * Methods to use when ordering `MatchmakingQueue`.
 */
public enum MatchmakingQueuesOrderBy {

    NATURAL("NATURAL"),
    PRIMARY_KEY_ASC("PRIMARY_KEY_ASC"),
    PRIMARY_KEY_DESC("PRIMARY_KEY_DESC"),
    ID_ASC("ID_ASC"),
    ID_DESC("ID_DESC"),
    NAME_ASC("NAME_ASC"),
    NAME_DESC("NAME_DESC"),
    BOT_OPPONENT_ASC("BOT_OPPONENT_ASC"),
    BOT_OPPONENT_DESC("BOT_OPPONENT_DESC"),
    PRIVATE_LOBBY_ASC("PRIVATE_LOBBY_ASC"),
    PRIVATE_LOBBY_DESC("PRIVATE_LOBBY_DESC"),
    STARTS_AUTOMATICALLY_ASC("STARTS_AUTOMATICALLY_ASC"),
    STARTS_AUTOMATICALLY_DESC("STARTS_AUTOMATICALLY_DESC"),
    STILL_CONNECTED_TIMEOUT_ASC("STILL_CONNECTED_TIMEOUT_ASC"),
    STILL_CONNECTED_TIMEOUT_DESC("STILL_CONNECTED_TIMEOUT_DESC"),
    EMPTY_LOBBY_TIMEOUT_ASC("EMPTY_LOBBY_TIMEOUT_ASC"),
    EMPTY_LOBBY_TIMEOUT_DESC("EMPTY_LOBBY_TIMEOUT_DESC"),
    AWAITING_LOBBY_TIMEOUT_ASC("AWAITING_LOBBY_TIMEOUT_ASC"),
    AWAITING_LOBBY_TIMEOUT_DESC("AWAITING_LOBBY_TIMEOUT_DESC"),
    ONCE_ASC("ONCE_ASC"),
    ONCE_DESC("ONCE_DESC"),
    AUTOMATICALLY_CLOSE_ASC("AUTOMATICALLY_CLOSE_ASC"),
    AUTOMATICALLY_CLOSE_DESC("AUTOMATICALLY_CLOSE_DESC"),
    LOBBY_SIZE_ASC("LOBBY_SIZE_ASC"),
    LOBBY_SIZE_DESC("LOBBY_SIZE_DESC"),
    QUEUE_CREATED_AT_ASC("QUEUE_CREATED_AT_ASC"),
    QUEUE_CREATED_AT_DESC("QUEUE_CREATED_AT_DESC");

    private final String graphqlName;

    private MatchmakingQueuesOrderBy(String graphqlName) {
        this.graphqlName = graphqlName;
    }

    @Override
    public String toString() {
        return this.graphqlName;
    }

}
