/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IClientScope extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.client_scope.id</code>.
     */
    public IClientScope setId(String value);

    /**
     * Getter for <code>public.client_scope.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.client_scope.name</code>.
     */
    public IClientScope setName(String value);

    /**
     * Getter for <code>public.client_scope.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>public.client_scope.realm_id</code>.
     */
    public IClientScope setRealmId(String value);

    /**
     * Getter for <code>public.client_scope.realm_id</code>.
     */
    public String getRealmId();

    /**
     * Setter for <code>public.client_scope.description</code>.
     */
    public IClientScope setDescription(String value);

    /**
     * Getter for <code>public.client_scope.description</code>.
     */
    public String getDescription();

    /**
     * Setter for <code>public.client_scope.protocol</code>.
     */
    public IClientScope setProtocol(String value);

    /**
     * Getter for <code>public.client_scope.protocol</code>.
     */
    public String getProtocol();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IClientScope
     */
    public void from(IClientScope from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IClientScope
     */
    public <E extends IClientScope> E into(E into);

    @Override
    public default IClientScope fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getString("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setRealmId(json.getString("realm_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("realm_id","java.lang.String",e);
        }
        try {
            setDescription(json.getString("description"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("description","java.lang.String",e);
        }
        try {
            setProtocol(json.getString("protocol"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("protocol","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("name",getName());
        json.put("realm_id",getRealmId());
        json.put("description",getDescription());
        json.put("protocol",getProtocol());
        return json;
    }

}
