version: '3'
services:
  loadbalancer:
    restart: always
    image: traefik:alpine
    command: |
      --debug \
      --api \
      --docker \
      --entryPoints="Name:http Address::80" \
      --retry \
      --docker.exposedbydefault=true
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - loadbalancerdata:/data
    deploy:
      labels:
      - "traefik.frontend.rule=PathPrefixStrip:/admin/traefik/"
      - "traefik.frontend.entryPoints=http"
      - "traefik.port=8080"
  game:
    restart: always
    image: doctorpangloss/spellsource:latest
    environment:
    - MONGO_URL=mongodb://mongo:27017/metastone
    - HAZELCAST_URLS=spellsource-server_game_1:5701
    - HAZELCAST_MANCENTER_URL=http://hazelcastmancenter:8080/admin/mancenter
    deploy:
      labels:
      - "traefik.frontend.rule=PathPrefixStrip:/api/v2/"
      - "traefik.frontend.entryPoints=http"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.backend.healthcheck.path=/"
      - "traefik.port=80"
  mongo:
    restart: always
    # Latest version fully supported by Spellsource
    image: "mongo:3.4.1"
    volumes:
    - mongodata:/data/db
    deploy:
      labels:
      - "traefik.enable=false"
  hazelcastmancenter:
    image: hazelcast/management-center
    volumes:
    - mancenterdata:/data
    environment:
    - MC_CONTEXT=/admin/mancenter
    - MANCENTER_DATA=/data
    - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    deploy:
      labels:
      - "traefik.frontend.rule=PathPrefix:/admin/mancenter/"
      - "traefik.frontend.entryPoints=http"
      - "traefik.port=8080"
volumes:
  mongodata:
  mancenterdata:
  portainerdata:
  loadbalancerdata: