# helm install jaeger jaegertracing/jaeger
provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false
storage:
  type: cassandra
  cassandra:
    host: cassandra.default.svc.cluster.local
    user: cassandra
    password: password
    extraEnv:
      - name: CASSANDRA_SERVERS
        value: cassandra.default.svc.cluster.local
      - name: CASSANDRA_PASSWORD
        value: password
      - name: CASSANDRA_USER
        value: cassandra
      - name: CASSANDRA_USERNAME
        value: cassandra
agent:
  service:
    type: ClusterIP