# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install -f keycloak-values.yaml keycloak bitnami/keycloak
rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list
replicaCount: 2
resources:
  requests:
    memory: 2G
    cpu: 200m
serviceDiscovery:
  enabled: true
metrics:
  # port 9990 by default for prometheus
  enabled: true
auth:
  adminPassword: password
  adminUser: admin
postgresql:
  enabled: false
externalDatabase:
  host: postgres-postgresql-ha-pgpool.default.svc.cluster.local
  port: 5432
  user: postgres
  password: password
  database: spellsource
extraEnvVars:
  - name: KEYCLOAK_DATABASE_SCHEMA
    value: "keycloak"
image:
  repository: doctorpangloss/keycloak-clustered
  tag: latest
  registry: docker.io
  pullPolicy: Always
service:
  port: 9090
  httpsPort: 9091