# helm install -f redis-values.yaml redis bitnami/redis
configmap: |-
  notify-keyspace-events Exg
usePassword: false
metrics:
  prometheusRule:
    enabled: true
master:
  persistence:
    enabled: false
  disableCommands: []
slave:
  persistence:
    enabled: false
  disableCommands: []
