# this is a values yaml designed for local debugging and not a production deployment
redis:
  enabled: false
postgresql:
  enabled: false
keycloak:
  enabled: false
configmap:
  pg:
    host: "postgres-postgresql-ha-pgpool.default.svc.cluster.local"
    user: "postgres"
    password: "password"
    database: "spellsource"
    port: 5432
  keycloak:
    # keycloak port is 8080 by default on bitnami images, and we override it to 9090
    authUrl: "http://keycloak.default.svc.cluster.local:9090/auth/"
    adminUsername: "admin"
    adminPassword: "password"
  redis:
    uri: "redis://redis-master.default.svc.cluster.local:6379"
  jaeger:
    enabled: true
    agentHost: "jaeger-agent.default.svc.cluster.local"
    agentPort: 6831
extraJavaOptions: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
extraPorts:
  - name: javadebug
    containerPort: 5005
    protocol: TCP
migration:
  resources:
    requests:
      cpu: 200m
      memory: 8Gi
logback: |
  import ch.qos.logback.classic.filter.ThresholdFilter

  appender("STDOUT", ConsoleAppender) {
      encoder(PatternLayoutEncoder) {
          pattern = "%level %logger{24} %msg%n"
      }

      filter(ThresholdFilter) {
          level = TRACE
      }
  }

  scan("1 seconds")

  root(ERROR, ["STDOUT"])