# this is a values yaml designed for local debugging and not a production deployment
redis:
  enabled: false
postgresql:
  enabled: false
keycloak:
  enabled: false
configmap:
  pg:
    host: "postgres-postgresql-ha-pgpool.default.svc.cluster.local"
    user: "postgres"
    password: "password"
    database: "spellsource"
    port: 5432
  keycloak:
    # keycloak port is 8080 by default on bitnami images, and we override it to 9090
    authUrl: "http://keycloak.default.svc.cluster.local:9090/"
    adminUsername: "admin"
    adminPassword: "password"
  redis:
    uri: "redis://redis-master.default.svc.cluster.local:6379"
  jaeger:
    enabled: true
    agentHost: "jaeger-agent.default.svc.cluster.local"
    agentPort: 6831
extraJavaOptions: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
extraPorts:
  - name: javadebug
    containerPort: 5005
    protocol: TCP
migration:
  resources:
    requests:
      cpu: 200m
      memory: 4Gi
logback: |
  <?xml version="1.0" encoding="UTF-8" ?>
  <!DOCTYPE configuration>

  <configuration
          xmlns="http://ch.qos.logback/xml/ns/logback"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://ch.qos.logback/xml/ns/logback https://raw.githubusercontent.com/enricopulatzo/logback-XSD/master/src/main/xsd/logback.xsd">
    <import class="ch.qos.logback.classic.encoder.PatternLayoutEncoder"/>
    <import class="ch.qos.logback.core.ConsoleAppender"/>

    <appender name="STDOUT" class="ConsoleAppender">
      <encoder class="PatternLayoutEncoder">
        <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
      </encoder>
    </appender>

    <root level="WARN">
      <appender-ref ref="STDOUT"/>
    </root>
    <logger name="io.jaegertracing" level="OFF" />
  </configuration>