/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.spellsource.tables.records;


import com.hiddenswitch.framework.schema.spellsource.enums.GameUserVictoryEnum;
import com.hiddenswitch.framework.schema.spellsource.tables.GameUsers;
import com.hiddenswitch.framework.schema.spellsource.tables.interfaces.IGameUsers;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameUsersRecord extends UpdatableRecordImpl<GameUsersRecord> implements VertxPojo, Record5<Short, Long, String, String, GameUserVictoryEnum>, IGameUsers {

    private static final long serialVersionUID = 1014468129;

    /**
     * Setter for <code>spellsource.game_users.player_index</code>.
     */
    @Override
    public GameUsersRecord setPlayerIndex(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>spellsource.game_users.player_index</code>.
     */
    @Override
    public Short getPlayerIndex() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>spellsource.game_users.game_id</code>.
     */
    @Override
    public GameUsersRecord setGameId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>spellsource.game_users.game_id</code>.
     */
    @Override
    public Long getGameId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>spellsource.game_users.user_id</code>.
     */
    @Override
    public GameUsersRecord setUserId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>spellsource.game_users.user_id</code>.
     */
    @Override
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>spellsource.game_users.deck_id</code>.
     */
    @Override
    public GameUsersRecord setDeckId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>spellsource.game_users.deck_id</code>.
     */
    @Override
    public String getDeckId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>spellsource.game_users.victory_status</code>.
     */
    @Override
    public GameUsersRecord setVictoryStatus(GameUserVictoryEnum value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>spellsource.game_users.victory_status</code>.
     */
    @Override
    public GameUserVictoryEnum getVictoryStatus() {
        return (GameUserVictoryEnum) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Short, Long, String, String, GameUserVictoryEnum> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Short, Long, String, String, GameUserVictoryEnum> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return GameUsers.GAME_USERS.PLAYER_INDEX;
    }

    @Override
    public Field<Long> field2() {
        return GameUsers.GAME_USERS.GAME_ID;
    }

    @Override
    public Field<String> field3() {
        return GameUsers.GAME_USERS.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return GameUsers.GAME_USERS.DECK_ID;
    }

    @Override
    public Field<GameUserVictoryEnum> field5() {
        return GameUsers.GAME_USERS.VICTORY_STATUS;
    }

    @Override
    public Short component1() {
        return getPlayerIndex();
    }

    @Override
    public Long component2() {
        return getGameId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getDeckId();
    }

    @Override
    public GameUserVictoryEnum component5() {
        return getVictoryStatus();
    }

    @Override
    public Short value1() {
        return getPlayerIndex();
    }

    @Override
    public Long value2() {
        return getGameId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getDeckId();
    }

    @Override
    public GameUserVictoryEnum value5() {
        return getVictoryStatus();
    }

    @Override
    public GameUsersRecord value1(Short value) {
        setPlayerIndex(value);
        return this;
    }

    @Override
    public GameUsersRecord value2(Long value) {
        setGameId(value);
        return this;
    }

    @Override
    public GameUsersRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public GameUsersRecord value4(String value) {
        setDeckId(value);
        return this;
    }

    @Override
    public GameUsersRecord value5(GameUserVictoryEnum value) {
        setVictoryStatus(value);
        return this;
    }

    @Override
    public GameUsersRecord values(Short value1, Long value2, String value3, String value4, GameUserVictoryEnum value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGameUsers from) {
        setPlayerIndex(from.getPlayerIndex());
        setGameId(from.getGameId());
        setUserId(from.getUserId());
        setDeckId(from.getDeckId());
        setVictoryStatus(from.getVictoryStatus());
    }

    @Override
    public <E extends IGameUsers> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameUsersRecord
     */
    public GameUsersRecord() {
        super(GameUsers.GAME_USERS);
    }

    /**
     * Create a detached, initialised GameUsersRecord
     */
    public GameUsersRecord(Short playerIndex, Long gameId, String userId, String deckId, GameUserVictoryEnum victoryStatus) {
        super(GameUsers.GAME_USERS);

        set(0, playerIndex);
        set(1, gameId);
        set(2, userId);
        set(3, deckId);
        set(4, victoryStatus);
    }

    public GameUsersRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
