/**
 * Hidden Switch Minionate API
 * The Minionate API for matchmaking, user accounts, collections management and more
 *
 * OpenAPI spec version: 1.0.1
 * Contact: benjamin.s.berman@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.hiddenswitch.proto3.net.client.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hiddenswitch.proto3.net.client.models.MatchmakingDeck;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * MatchmakingQueuePutRequest
 */

public class MatchmakingQueuePutRequest  implements Serializable {
  @SerializedName("casual")
  private Boolean casual = null;

  @SerializedName("deckId")
  private String deckId = null;

  @SerializedName("deck")
  private MatchmakingDeck deck = null;

  public MatchmakingQueuePutRequest casual(Boolean casual) {
    this.casual = casual;
    return this;
  }

   /**
   * Get casual
   * @return casual
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getCasual() {
    return casual;
  }

  public void setCasual(Boolean casual) {
    this.casual = casual;
  }

  public MatchmakingQueuePutRequest deckId(String deckId) {
    this.deckId = deckId;
    return this;
  }

   /**
   * Get deckId
   * @return deckId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeckId() {
    return deckId;
  }

  public void setDeckId(String deckId) {
    this.deckId = deckId;
  }

  public MatchmakingQueuePutRequest deck(MatchmakingDeck deck) {
    this.deck = deck;
    return this;
  }

   /**
   * Get deck
   * @return deck
  **/
  @ApiModelProperty(example = "null", value = "")
  public MatchmakingDeck getDeck() {
    return deck;
  }

  public void setDeck(MatchmakingDeck deck) {
    this.deck = deck;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchmakingQueuePutRequest matchmakingQueuePutRequest = (MatchmakingQueuePutRequest) o;
    return Objects.equals(this.casual, matchmakingQueuePutRequest.casual) &&
        Objects.equals(this.deckId, matchmakingQueuePutRequest.deckId) &&
        Objects.equals(this.deck, matchmakingQueuePutRequest.deck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(casual, deckId, deck);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchmakingQueuePutRequest {\n");
    
    sb.append("    casual: ").append(toIndentedString(casual)).append("\n");
    sb.append("    deckId: ").append(toIndentedString(deckId)).append("\n");
    sb.append("    deck: ").append(toIndentedString(deck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

