/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.tables.records;


import com.hiddenswitch.framework.schema.tables.ScopeMapping;
import com.hiddenswitch.framework.schema.tables.interfaces.IScopeMapping;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScopeMappingRecord extends UpdatableRecordImpl<ScopeMappingRecord> implements VertxPojo, Record2<String, String>, IScopeMapping {

    private static final long serialVersionUID = -2014328692;

    /**
     * Setter for <code>public.scope_mapping.client_id</code>.
     */
    @Override
    public ScopeMappingRecord setClientId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.scope_mapping.client_id</code>.
     */
    @Override
    public String getClientId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.scope_mapping.role_id</code>.
     */
    @Override
    public ScopeMappingRecord setRoleId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.scope_mapping.role_id</code>.
     */
    @Override
    public String getRoleId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ScopeMapping.SCOPE_MAPPING.CLIENT_ID;
    }

    @Override
    public Field<String> field2() {
        return ScopeMapping.SCOPE_MAPPING.ROLE_ID;
    }

    @Override
    public String component1() {
        return getClientId();
    }

    @Override
    public String component2() {
        return getRoleId();
    }

    @Override
    public String value1() {
        return getClientId();
    }

    @Override
    public String value2() {
        return getRoleId();
    }

    @Override
    public ScopeMappingRecord value1(String value) {
        setClientId(value);
        return this;
    }

    @Override
    public ScopeMappingRecord value2(String value) {
        setRoleId(value);
        return this;
    }

    @Override
    public ScopeMappingRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IScopeMapping from) {
        setClientId(from.getClientId());
        setRoleId(from.getRoleId());
    }

    @Override
    public <E extends IScopeMapping> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScopeMappingRecord
     */
    public ScopeMappingRecord() {
        super(ScopeMapping.SCOPE_MAPPING);
    }

    /**
     * Create a detached, initialised ScopeMappingRecord
     */
    public ScopeMappingRecord(String clientId, String roleId) {
        super(ScopeMapping.SCOPE_MAPPING);

        set(0, clientId);
        set(1, roleId);
    }

    public ScopeMappingRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
