/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.records;


import com.hiddenswitch.framework.schema.keycloak.tables.ResourcePolicy;
import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IResourcePolicy;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResourcePolicyRecord extends UpdatableRecordImpl<ResourcePolicyRecord> implements VertxPojo, Record2<String, String>, IResourcePolicy {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>keycloak.resource_policy.resource_id</code>.
     */
    @Override
    public ResourcePolicyRecord setResourceId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>keycloak.resource_policy.resource_id</code>.
     */
    @Override
    public String getResourceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>keycloak.resource_policy.policy_id</code>.
     */
    @Override
    public ResourcePolicyRecord setPolicyId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>keycloak.resource_policy.policy_id</code>.
     */
    @Override
    public String getPolicyId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ResourcePolicy.RESOURCE_POLICY.RESOURCE_ID;
    }

    @Override
    public Field<String> field2() {
        return ResourcePolicy.RESOURCE_POLICY.POLICY_ID;
    }

    @Override
    public String component1() {
        return getResourceId();
    }

    @Override
    public String component2() {
        return getPolicyId();
    }

    @Override
    public String value1() {
        return getResourceId();
    }

    @Override
    public String value2() {
        return getPolicyId();
    }

    @Override
    public ResourcePolicyRecord value1(String value) {
        setResourceId(value);
        return this;
    }

    @Override
    public ResourcePolicyRecord value2(String value) {
        setPolicyId(value);
        return this;
    }

    @Override
    public ResourcePolicyRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IResourcePolicy from) {
        setResourceId(from.getResourceId());
        setPolicyId(from.getPolicyId());
    }

    @Override
    public <E extends IResourcePolicy> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResourcePolicyRecord
     */
    public ResourcePolicyRecord() {
        super(ResourcePolicy.RESOURCE_POLICY);
    }

    /**
     * Create a detached, initialised ResourcePolicyRecord
     */
    public ResourcePolicyRecord(String resourceId, String policyId) {
        super(ResourcePolicy.RESOURCE_POLICY);

        setResourceId(resourceId);
        setPolicyId(policyId);
    }

    /**
     * Create a detached, initialised ResourcePolicyRecord
     */
    public ResourcePolicyRecord(com.hiddenswitch.framework.schema.keycloak.tables.pojos.ResourcePolicy value) {
        super(ResourcePolicy.RESOURCE_POLICY);

        if (value != null) {
            setResourceId(value.getResourceId());
            setPolicyId(value.getPolicyId());
        }
    }

        public ResourcePolicyRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
