/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.records;


import com.hiddenswitch.framework.schema.keycloak.tables.UserConsentProtMapper;
import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IUserConsentProtMapper;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConsentProtMapperRecord extends UpdatableRecordImpl<UserConsentProtMapperRecord> implements VertxPojo, Record2<String, String>, IUserConsentProtMapper {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>keycloak.user_consent_prot_mapper.user_consent_id</code>.
     */
    @Override
    public UserConsentProtMapperRecord setUserConsentId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>keycloak.user_consent_prot_mapper.user_consent_id</code>.
     */
    @Override
    public String getUserConsentId() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>keycloak.user_consent_prot_mapper.protocol_mapper_id</code>.
     */
    @Override
    public UserConsentProtMapperRecord setProtocolMapperId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>keycloak.user_consent_prot_mapper.protocol_mapper_id</code>.
     */
    @Override
    public String getProtocolMapperId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return UserConsentProtMapper.USER_CONSENT_PROT_MAPPER.USER_CONSENT_ID;
    }

    @Override
    public Field<String> field2() {
        return UserConsentProtMapper.USER_CONSENT_PROT_MAPPER.PROTOCOL_MAPPER_ID;
    }

    @Override
    public String component1() {
        return getUserConsentId();
    }

    @Override
    public String component2() {
        return getProtocolMapperId();
    }

    @Override
    public String value1() {
        return getUserConsentId();
    }

    @Override
    public String value2() {
        return getProtocolMapperId();
    }

    @Override
    public UserConsentProtMapperRecord value1(String value) {
        setUserConsentId(value);
        return this;
    }

    @Override
    public UserConsentProtMapperRecord value2(String value) {
        setProtocolMapperId(value);
        return this;
    }

    @Override
    public UserConsentProtMapperRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserConsentProtMapper from) {
        setUserConsentId(from.getUserConsentId());
        setProtocolMapperId(from.getProtocolMapperId());
    }

    @Override
    public <E extends IUserConsentProtMapper> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserConsentProtMapperRecord
     */
    public UserConsentProtMapperRecord() {
        super(UserConsentProtMapper.USER_CONSENT_PROT_MAPPER);
    }

    /**
     * Create a detached, initialised UserConsentProtMapperRecord
     */
    public UserConsentProtMapperRecord(String userConsentId, String protocolMapperId) {
        super(UserConsentProtMapper.USER_CONSENT_PROT_MAPPER);

        setUserConsentId(userConsentId);
        setProtocolMapperId(protocolMapperId);
    }

    /**
     * Create a detached, initialised UserConsentProtMapperRecord
     */
    public UserConsentProtMapperRecord(com.hiddenswitch.framework.schema.keycloak.tables.pojos.UserConsentProtMapper value) {
        super(UserConsentProtMapper.USER_CONSENT_PROT_MAPPER);

        if (value != null) {
            setUserConsentId(value.getUserConsentId());
            setProtocolMapperId(value.getProtocolMapperId());
        }
    }

        public UserConsentProtMapperRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
