global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'vertx'
    static_configs:
      - targets: ['host.testcontainers.internal:8081']
  - job_name: 'promswarmconnect'
    relabel_configs:
      - source_labels: [__meta_triton_machine_image]
        target_label: job
      - source_labels: [__meta_triton_machine_id]
        target_label: instance
      - source_labels: [__meta_triton_machine_alias]
        target_label: __address__
      - source_labels: [__meta_triton_server_id]
        target_label: __metrics_path__
    triton_sd_configs:
      - account: 'username'
        dns_suffix: 'dnssuffix'
        endpoint: 'promswarmconnect'
        port: 443
        refresh_interval: 5s
        version: 1
        tls_config:
          insecure_skip_verify: true