/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.hiddenswitch.tables.daos;


import com.hiddenswitch.framework.schema.hiddenswitch.tables.FlywaySchemaHistory;
import com.hiddenswitch.framework.schema.hiddenswitch.tables.records.FlywaySchemaHistoryRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Configuration;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistoryDao extends AbstractReactiveVertxDAO<FlywaySchemaHistoryRecord, com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory, Integer, Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>>, Future<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>, Future<Integer>, Future<Integer>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<FlywaySchemaHistoryRecord,com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory,Integer> {

        /**
     * @param configuration Used for rendering, so only SQLDialect must be set
     * and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query
     * execution
     */
        public FlywaySchemaHistoryDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
                super(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory.class, new ReactiveClassicQueryExecutor<FlywaySchemaHistoryRecord,com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory,Integer>(configuration,delegate,com.hiddenswitch.framework.schema.hiddenswitch.tables.mappers.RowMappers.getFlywaySchemaHistoryMapper()));
        }

        @Override
        protected Integer getId(com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory object) {
                return object.getInstalledRank();
        }

        /**
     * Find records that have <code>version IN (values)</code> asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByVersion(Collection<String> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.VERSION.in(values));
        }

        /**
     * Find records that have <code>version IN (values)</code> asynchronously
     * limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByVersion(Collection<String> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.VERSION.in(values),limit);
        }

        /**
     * Find records that have <code>description IN (values)</code>
     * asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByDescription(Collection<String> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.DESCRIPTION.in(values));
        }

        /**
     * Find records that have <code>description IN (values)</code>
     * asynchronously limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByDescription(Collection<String> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.DESCRIPTION.in(values),limit);
        }

        /**
     * Find records that have <code>type IN (values)</code> asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByType(Collection<String> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.TYPE.in(values));
        }

        /**
     * Find records that have <code>type IN (values)</code> asynchronously
     * limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByType(Collection<String> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.TYPE.in(values),limit);
        }

        /**
     * Find records that have <code>script IN (values)</code> asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByScript(Collection<String> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SCRIPT.in(values));
        }

        /**
     * Find records that have <code>script IN (values)</code> asynchronously
     * limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByScript(Collection<String> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SCRIPT.in(values),limit);
        }

        /**
     * Find records that have <code>checksum IN (values)</code> asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByChecksum(Collection<Integer> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.CHECKSUM.in(values));
        }

        /**
     * Find records that have <code>checksum IN (values)</code> asynchronously
     * limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByChecksum(Collection<Integer> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.CHECKSUM.in(values),limit);
        }

        /**
     * Find records that have <code>installed_by IN (values)</code>
     * asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByInstalledBy(Collection<String> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_BY.in(values));
        }

        /**
     * Find records that have <code>installed_by IN (values)</code>
     * asynchronously limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByInstalledBy(Collection<String> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_BY.in(values),limit);
        }

        /**
     * Find records that have <code>installed_on IN (values)</code>
     * asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByInstalledOn(Collection<LocalDateTime> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_ON.in(values));
        }

        /**
     * Find records that have <code>installed_on IN (values)</code>
     * asynchronously limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByInstalledOn(Collection<LocalDateTime> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_ON.in(values),limit);
        }

        /**
     * Find records that have <code>execution_time IN (values)</code>
     * asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByExecutionTime(Collection<Integer> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.EXECUTION_TIME.in(values));
        }

        /**
     * Find records that have <code>execution_time IN (values)</code>
     * asynchronously limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyByExecutionTime(Collection<Integer> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.EXECUTION_TIME.in(values),limit);
        }

        /**
     * Find records that have <code>success IN (values)</code> asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyBySuccess(Collection<Boolean> values) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS.in(values));
        }

        /**
     * Find records that have <code>success IN (values)</code> asynchronously
     * limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory>> findManyBySuccess(Collection<Boolean> values, int limit) {
                return findManyByCondition(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS.in(values),limit);
        }

        @Override
        public ReactiveClassicQueryExecutor<FlywaySchemaHistoryRecord,com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory,Integer> queryExecutor(){
                return (ReactiveClassicQueryExecutor<FlywaySchemaHistoryRecord,com.hiddenswitch.framework.schema.hiddenswitch.tables.pojos.FlywaySchemaHistory,Integer>) super.queryExecutor();
        }
}
