/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables;


import com.hiddenswitch.framework.schema.keycloak.Indexes;
import com.hiddenswitch.framework.schema.keycloak.Keycloak;
import com.hiddenswitch.framework.schema.keycloak.Keys;
import com.hiddenswitch.framework.schema.keycloak.tables.records.UserConsentClientScopeRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserConsentClientScope extends TableImpl<UserConsentClientScopeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>keycloak.user_consent_client_scope</code>
     */
    public static final UserConsentClientScope USER_CONSENT_CLIENT_SCOPE = new UserConsentClientScope();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserConsentClientScopeRecord> getRecordType() {
        return UserConsentClientScopeRecord.class;
    }

    /**
     * The column
     * <code>keycloak.user_consent_client_scope.user_consent_id</code>.
     */
    public final TableField<UserConsentClientScopeRecord, String> USER_CONSENT_ID = createField(DSL.name("user_consent_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>keycloak.user_consent_client_scope.scope_id</code>.
     */
    public final TableField<UserConsentClientScopeRecord, String> SCOPE_ID = createField(DSL.name("scope_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    private UserConsentClientScope(Name alias, Table<UserConsentClientScopeRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserConsentClientScope(Name alias, Table<UserConsentClientScopeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>keycloak.user_consent_client_scope</code> table
     * reference
     */
    public UserConsentClientScope(String alias) {
        this(DSL.name(alias), USER_CONSENT_CLIENT_SCOPE);
    }

    /**
     * Create an aliased <code>keycloak.user_consent_client_scope</code> table
     * reference
     */
    public UserConsentClientScope(Name alias) {
        this(alias, USER_CONSENT_CLIENT_SCOPE);
    }

    /**
     * Create a <code>keycloak.user_consent_client_scope</code> table reference
     */
    public UserConsentClientScope() {
        this(DSL.name("user_consent_client_scope"), null);
    }

    public <O extends Record> UserConsentClientScope(Table<O> child, ForeignKey<O, UserConsentClientScopeRecord> key) {
        super(child, key, USER_CONSENT_CLIENT_SCOPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Keycloak.KEYCLOAK;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USCONSENT_CLSCOPE);
    }

    @Override
    public UniqueKey<UserConsentClientScopeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_GRNTCSNT_CLSC_PM;
    }

    @Override
    public List<ForeignKey<UserConsentClientScopeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_CONSENT_CLIENT_SCOPE__FK_GRNTCSNT_CLSC_USC);
    }

    private transient UserConsent _userConsent;

    /**
     * Get the implicit join path to the <code>keycloak.user_consent</code>
     * table.
     */
    public UserConsent userConsent() {
        if (_userConsent == null)
            _userConsent = new UserConsent(this, Keys.USER_CONSENT_CLIENT_SCOPE__FK_GRNTCSNT_CLSC_USC);

        return _userConsent;
    }

    @Override
    public UserConsentClientScope as(String alias) {
        return new UserConsentClientScope(DSL.name(alias), this);
    }

    @Override
    public UserConsentClientScope as(Name alias) {
        return new UserConsentClientScope(alias, this);
    }

    @Override
    public UserConsentClientScope as(Table<?> alias) {
        return new UserConsentClientScope(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserConsentClientScope rename(String name) {
        return new UserConsentClientScope(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserConsentClientScope rename(Name name) {
        return new UserConsentClientScope(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserConsentClientScope rename(Table<?> name) {
        return new UserConsentClientScope(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
