api:
  minimatch:
    grpcport: 50509
  backend:
    hostname: localhost
    grpcport: 50509
  frontend:
    hostname: localhost
    grpcport: 50509
  query:
    hostname: localhost
    grpcport: 50509
  synchronizer:
    hostname: localhost
    grpcport: 50509
redis:
  # BYO Redis setups
  hostname: localhost
  port: 6379
  user: "admin"