{{- $configMap := toYaml .Values.configmap -}}
{{- $logback := .Values.logback -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spellsource.fullname" . }}
  labels:
    app: {{ template "spellsource.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  spellsource-config.yaml: |
    # Dummy comment: https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/yaml_techniques.md#strings-in-yaml
{{ tpl $configMap . | indent 4 }}
  logback.xml: |
{{ tpl $logback . | indent 4 }}