apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spellsource.fullname" . }}
  labels:
    {{- include "spellsource.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "spellsource.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spellsource.selectorLabels" . | nindent 8 }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spellsource.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: "-Djgroups.dns.query={{ include "spellsource.fullname" . }}internal.{{ .Release.Namespace }}.svc.cluster.local -Dlogback.configurationFile=/app/logback.groovy {{ .Values.extraJavaOptions }}"
          {{- if .Values.configmap.jaeger.enabled}}
            - name: "JAEGER_AGENT_HOST"
              value: {{ .Values.configmap.jaeger.agentHost | quote }}
            - name: "JAEGER_AGENT_PORT"
              value: {{ .Values.configmap.jaeger.agentPort | quote }}
          {{- end}}
          {{- if .Values.extraEnv }}
            # Extra environment variables
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.configmap.grpcConfiguration.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.configmap.metrics.port }}
              protocol: TCP
            - name: infinispan
              containerPort: 7800
              protocol: TCP
          {{- if .Values.extraPorts }}
            {{- toYaml .Values.extraPorts | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.configmap.metrics.livenessRoute }}
              port: http
            initialDelaySeconds: 16
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.configmap.metrics.readinessRoute }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: {{ .Values.configmap.metrics.readinessRoute }}
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config-volume
            mountPath: /conf
          - name: config-volume
            mountPath: /app/logback.groovy
            subPath: logback.groovy
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "spellsource.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
