kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "spellsource.fullname" . }}-read-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "spellsource.fullname" . }}-read-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "spellsource.fullname" . }}-read-pods
subjects:
  - kind: ServiceAccount
    name: {{ include "spellsource.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
