plugins {
    id 'java-library'
}

apply from: '../gradle/instrument.gradle'

group 'com.hiddenswitch'

dependencies {
    implementation project(':spellsource-common')
    api project(':spellsource-protos')
    testImplementation 'org.jetbrains:annotations'
    testImplementation "com.google.guava:guava:$guavaVersion"
    testImplementation project(':spellsource-testutils')
    testImplementation project(':spellsource-cards-git')
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
    testImplementation "ch.qos.logback:logback-classic:$logbackVersion"
}

test {
    useJUnitPlatform()
    testLogging {
        events "standardError"
    }
    enableAssertions = false
}

tasks.register('jshell', JavaExec) {
    dependsOn testClasses
    jvmArgs = ['--add-modules', 'jdk.jshell']
    classpath = files()
    mainClass = 'jdk.internal.jshell.tool.JShellToolProvider'
    args = ['--enable-preview', '--class-path', sourceSets.test.runtimeClasspath.asPath]
    standardInput = System.in
}

tasks.register('diagnose', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.hiddenswitch.spellsource.tests.hearthstone.TraceDiagnostics'
    jvmArgs = ['--enable-preview']
}

tasks.register('replay', JavaExec) {
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.hiddenswitch.spellsource.tests.hearthstone.TraceReplay'
    jvmArgs = ['--enable-preview']
}