/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IClientTemplate;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientTemplate implements VertxPojo, IClientTemplate {

    private static final long serialVersionUID = 611792848;


    public ClientTemplate() {}

    public ClientTemplate(IClientTemplate value) {
    }

    public ClientTemplate(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClientTemplate (");


        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IClientTemplate from) {
    }

    @Override
    public <E extends IClientTemplate> E into(E into) {
        into.from(this);
        return into;
    }
}
