/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.ITemplateScopeMapping;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateScopeMapping implements VertxPojo, ITemplateScopeMapping {

    private static final long serialVersionUID = 873584236;


    public TemplateScopeMapping() {}

    public TemplateScopeMapping(ITemplateScopeMapping value) {
    }

    public TemplateScopeMapping(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TemplateScopeMapping (");


        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITemplateScopeMapping from) {
    }

    @Override
    public <E extends ITemplateScopeMapping> E into(E into) {
        into.from(this);
        return into;
    }
}
