package net.demilich.metastone.game.targeting;

public enum TargetSelection {
	NONE,
	ANY,
	MINIONS,
	ENEMY_CHARACTERS,
	FRIENDLY_CHARACTERS,
	ENEMY_MINIONS,
	FRIENDLY_MINIONS,
	FRIENDLY_HERO_AND_MINIONS,
	HEROES,
	ENEMY_HERO,
	FRIENDLY_HERO
}
