#!/bin/bash
./gradlew cluster:shadowJar
java -cp cluster/build/libs/cluster-1.2.0-all.jar com.hiddenswitch.cluster.applications.DeployCluster -appargs "-input s3n://clusterresults/$1 -gamesperbatch 1 -batches $2" -bucketname clustercode -instancecount $3 -bidprice $4
