#!/bin/bash
./gradlew cluster:shadowJar
spark-submit --master "local[8]" --class com.hiddenswitch.cluster.applications.LegacyDeckTester cluster/build/libs/cluster-1.2.0-all.jar -output s3n://clusterresults/$1 -gamesperbatch $2 -batches $3
