/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.tables;


import com.hiddenswitch.framework.schema.Indexes;
import com.hiddenswitch.framework.schema.Keys;
import com.hiddenswitch.framework.schema.Public;
import com.hiddenswitch.framework.schema.tables.records.AssociatedPolicyRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssociatedPolicy extends TableImpl<AssociatedPolicyRecord> {

    private static final long serialVersionUID = -11077362;

    /**
     * The reference instance of <code>public.associated_policy</code>
     */
    public static final AssociatedPolicy ASSOCIATED_POLICY = new AssociatedPolicy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssociatedPolicyRecord> getRecordType() {
        return AssociatedPolicyRecord.class;
    }

    /**
     * The column <code>public.associated_policy.policy_id</code>.
     */
    public final TableField<AssociatedPolicyRecord, String> POLICY_ID = createField(DSL.name("policy_id"), org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.associated_policy.associated_policy_id</code>.
     */
    public final TableField<AssociatedPolicyRecord, String> ASSOCIATED_POLICY_ID = createField(DSL.name("associated_policy_id"), org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.associated_policy</code> table reference
     */
    public AssociatedPolicy() {
        this(DSL.name("associated_policy"), null);
    }

    /**
     * Create an aliased <code>public.associated_policy</code> table reference
     */
    public AssociatedPolicy(String alias) {
        this(DSL.name(alias), ASSOCIATED_POLICY);
    }

    /**
     * Create an aliased <code>public.associated_policy</code> table reference
     */
    public AssociatedPolicy(Name alias) {
        this(alias, ASSOCIATED_POLICY);
    }

    private AssociatedPolicy(Name alias, Table<AssociatedPolicyRecord> aliased) {
        this(alias, aliased, null);
    }

    private AssociatedPolicy(Name alias, Table<AssociatedPolicyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AssociatedPolicy(Table<O> child, ForeignKey<O, AssociatedPolicyRecord> key) {
        super(child, key, ASSOCIATED_POLICY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_ASSOC_POL_ASSOC_POL_ID);
    }

    @Override
    public UniqueKey<AssociatedPolicyRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_FARSRPAP;
    }

    @Override
    public List<UniqueKey<AssociatedPolicyRecord>> getKeys() {
        return Arrays.<UniqueKey<AssociatedPolicyRecord>>asList(Keys.CONSTRAINT_FARSRPAP);
    }

    @Override
    public List<ForeignKey<AssociatedPolicyRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AssociatedPolicyRecord, ?>>asList(Keys.ASSOCIATED_POLICY__FK_FRSRPAS14XCX4WNKOG82SSRFY, Keys.ASSOCIATED_POLICY__FK_FRSR5S213XCX4WNKOG82SSRFY);
    }

    public ResourceServerPolicy fkFrsrpas14xcx4wnkog82ssrfy() {
        return new ResourceServerPolicy(this, Keys.ASSOCIATED_POLICY__FK_FRSRPAS14XCX4WNKOG82SSRFY);
    }

    public ResourceServerPolicy fkFrsr5s213xcx4wnkog82ssrfy() {
        return new ResourceServerPolicy(this, Keys.ASSOCIATED_POLICY__FK_FRSR5S213XCX4WNKOG82SSRFY);
    }

    @Override
    public AssociatedPolicy as(String alias) {
        return new AssociatedPolicy(DSL.name(alias), this);
    }

    @Override
    public AssociatedPolicy as(Name alias) {
        return new AssociatedPolicy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssociatedPolicy rename(String name) {
        return new AssociatedPolicy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssociatedPolicy rename(Name name) {
        return new AssociatedPolicy(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
