/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.spellsource.routines;


import com.hiddenswitch.framework.schema.spellsource.Spellsource;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckRogueGameStart extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>spellsource.check_rogue_game_start.deck_id</code>.
     */
    public static final Parameter<String> DECK_ID = Internal.createParameter("deck_id", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>spellsource.check_rogue_game_start.game_id</code>.
     */
    public static final Parameter<Long> GAME_ID = Internal.createParameter("game_id", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public CheckRogueGameStart() {
        super("check_rogue_game_start", Spellsource.SPELLSOURCE);

        addInParameter(DECK_ID);
        addInParameter(GAME_ID);
    }

    /**
     * Set the <code>deck_id</code> parameter IN value to the routine
     */
    public void setDeckId(String value) {
        setValue(DECK_ID, value);
    }

    /**
     * Set the <code>game_id</code> parameter IN value to the routine
     */
    public void setGameId(Long value) {
        setValue(GAME_ID, value);
    }
}
