/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.spellsource.routines;


import com.hiddenswitch.framework.schema.spellsource.Spellsource;
import com.hiddenswitch.framework.schema.spellsource.tables.records.RogueChoiceRecord;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentRogueChoice extends AbstractRoutine<RogueChoiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>spellsource.current_rogue_choice.RETURN_VALUE</code>.
     */
    public static final Parameter<RogueChoiceRecord> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", com.hiddenswitch.framework.schema.spellsource.tables.RogueChoice.ROGUE_CHOICE.getDataType(), false, false);

    /**
     * The parameter <code>spellsource.current_rogue_choice.rogue_id</code>.
     */
    public static final Parameter<Long> ROGUE_ID = Internal.createParameter("rogue_id", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public CurrentRogueChoice() {
        super("current_rogue_choice", Spellsource.SPELLSOURCE, com.hiddenswitch.framework.schema.spellsource.tables.RogueChoice.ROGUE_CHOICE.getDataType());

        setReturnParameter(RETURN_VALUE);
        addInParameter(ROGUE_ID);
    }

    /**
     * Set the <code>rogue_id</code> parameter IN value to the routine
     */
    public void setRogueId(Long value) {
        setValue(ROGUE_ID, value);
    }

    /**
     * Set the <code>rogue_id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public CurrentRogueChoice setRogueId(Field<Long> field) {
        setField(ROGUE_ID, field);
        return this;
    }
}
