export const attackToken: string
export const baseAttack: string
export const baseHp: string
export const baseManaCost: string
export const cardDisplayTemplate: string
export const description: string
export const descriptionBox: string
export const hero: string
export const heroAndShadow: string
export const heroShadow: string
export const highlight: string
export const hpToken: string
export const layerOne: string
export const name: string
export const pedestalPrimary: string
export const pedestalSecondary: string
export const pedestalShadow: string
export const primary: string
export const secondary: string
export const shadow: string
export const type: string
export const windowBackground: string
