package net.demilich.metastone.game.spells.desc.aura;

public enum AuraArg {
	CLASS,
	FILTER,
	TARGET,
	ATTRIBUTE,
	ATTACK_BONUS,
	HP_BONUS,
	APPLY_EFFECT,
	PAY_EFFECT,
	SECONDARY_TRIGGER,
	ALWAYS_APPLY,
	REVERT_TRIGGER,
	CONDITION,
	CARD,
	CAN_AFFORD_CONDITION,
	AMOUNT_OF_CURRENCY,
	TARGET_SELECTION,
	CHOOSE_ONE_OVERRIDE,
	REMOVE_EFFECT
}
