/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.daos;


import com.hiddenswitch.framework.schema.keycloak.tables.RealmEventsListeners;
import com.hiddenswitch.framework.schema.keycloak.tables.records.RealmEventsListenersRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.util.Collection;

import org.jooq.Configuration;
import org.jooq.Record2;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RealmEventsListenersDao extends AbstractReactiveVertxDAO<RealmEventsListenersRecord, com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners, Record2<String, String>, Future<List<com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners>>, Future<com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners>, Future<Integer>, Future<Record2<String, String>>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<RealmEventsListenersRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners,Record2<String, String>> {

        /**
     * @param configuration Used for rendering, so only SQLDialect must be set
     * and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query
     * execution
     */
        public RealmEventsListenersDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
                super(RealmEventsListeners.REALM_EVENTS_LISTENERS, com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners.class, new ReactiveClassicQueryExecutor<RealmEventsListenersRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners,Record2<String, String>>(configuration,delegate,com.hiddenswitch.framework.schema.keycloak.tables.mappers.RowMappers.getRealmEventsListenersMapper()));
        }

        @Override
        protected Record2<String, String> getId(com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners object) {
                return compositeKeyRecord(object.getRealmId(), object.getValue());
        }

        /**
     * Find records that have <code>value IN (values)</code> asynchronously
     */
        public Future<List<com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners>> findManyByValue(Collection<String> values) {
                return findManyByCondition(RealmEventsListeners.REALM_EVENTS_LISTENERS.VALUE.in(values));
        }

        /**
     * Find records that have <code>value IN (values)</code> asynchronously
     * limited by the given limit
     */
        public Future<List<com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners>> findManyByValue(Collection<String> values, int limit) {
                return findManyByCondition(RealmEventsListeners.REALM_EVENTS_LISTENERS.VALUE.in(values),limit);
        }

        @Override
        public ReactiveClassicQueryExecutor<RealmEventsListenersRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners,Record2<String, String>> queryExecutor(){
                return (ReactiveClassicQueryExecutor<RealmEventsListenersRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.RealmEventsListeners,Record2<String, String>>) super.queryExecutor();
        }
}
