/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.daos;


import com.hiddenswitch.framework.schema.keycloak.tables.WebOrigins;
import com.hiddenswitch.framework.schema.keycloak.tables.records.WebOriginsRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.util.Collection;

import org.jooq.Configuration;
import org.jooq.Record2;


import java.util.List;
import io.vertx.core.Future;
import io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebOriginsDao extends AbstractReactiveVertxDAO<WebOriginsRecord, com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins, Record2<String, String>, Future<List<com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins>>, Future<com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins>, Future<Integer>, Future<Record2<String, String>>> implements io.github.jklingsporn.vertx.jooq.classic.VertxDAO<WebOriginsRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins,Record2<String, String>> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the POSTGREs types.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public WebOriginsDao(Configuration configuration, io.vertx.sqlclient.SqlClient delegate) {
        super(WebOrigins.WEB_ORIGINS, com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins.class, new ReactiveClassicQueryExecutor<WebOriginsRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins,Record2<String, String>>(configuration,delegate,com.hiddenswitch.framework.schema.keycloak.tables.mappers.RowMappers.getWebOriginsMapper()));
    }

    @Override
    protected Record2<String, String> getId(com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins object) {
        return compositeKeyRecord(object.getClientId(), object.getValue());
    }

    /**
     * Find records that have <code>value IN (values)</code> asynchronously
     */
    public Future<List<com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins>> findManyByValue(Collection<String> values) {
        return findManyByCondition(WebOrigins.WEB_ORIGINS.VALUE.in(values));
    }

    /**
     * Find records that have <code>value IN (values)</code> asynchronously limited by the given limit
     */
    public Future<List<com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins>> findManyByValue(Collection<String> values, int limit) {
        return findManyByCondition(WebOrigins.WEB_ORIGINS.VALUE.in(values),limit);
    }

    @Override
    public ReactiveClassicQueryExecutor<WebOriginsRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins,Record2<String, String>> queryExecutor(){
        return (ReactiveClassicQueryExecutor<WebOriginsRecord,com.hiddenswitch.framework.schema.keycloak.tables.pojos.WebOrigins,Record2<String, String>>) super.queryExecutor();
    }
}
