/**
 * comfyui
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QueueTupleInner } from '../models/QueueTupleInner';
import { HttpFile } from '../http/http';

export class GetQueue200Response {
    'queueRunning'?: Array<Array<QueueTupleInner>>;
    'queuePending'?: Array<Array<QueueTupleInner>>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queueRunning",
            "baseName": "queue_running",
            "type": "Array<Array<QueueTupleInner>>",
            "format": ""
        },
        {
            "name": "queuePending",
            "baseName": "queue_pending",
            "type": "Array<Array<QueueTupleInner>>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetQueue200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

