/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.records;


import com.hiddenswitch.framework.schema.keycloak.tables.ClientIdentityProvMapping;
import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IClientIdentityProvMapping;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientIdentityProvMappingRecord extends TableRecordImpl<ClientIdentityProvMappingRecord> implements VertxPojo, IClientIdentityProvMapping {

    private static final long serialVersionUID = -1489237954;

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IClientIdentityProvMapping from) {
    }

    @Override
    public <E extends IClientIdentityProvMapping> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientIdentityProvMappingRecord
     */
    public ClientIdentityProvMappingRecord() {
        super(ClientIdentityProvMapping.CLIENT_IDENTITY_PROV_MAPPING);
    }

    public ClientIdentityProvMappingRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
