from spellsource.ext.cards import iter_card_and_file_path, write_card
import os
import re

CARDS = [
    'spell_cleanup_2',
    'spell_cleanup_3',
    'spell_hit_and_run',
    'spell_backstab',
    'spell_test_choose_one_3',
    'spell_test_choose_one_2',
    'spell_test_choose_one_1',
    'spell_death_strike',
    'spell_the_hunt',
    'spell_forgotten_torch',
    'spell_immolate',
    'spell_unnerfed_pyroblast',
    'spell_quick_shot',
    'spell_cleanup_1',
    'spell_holy_fire',
    'spell_maelstrom_portal',
    'spell_rogues_do_it',
    'spell_lightning_bolt',
    'spell_roaring_torch',
    'spell_lesser_jasper_spellstone',
    'spell_appetizer',
    'spell_demand',
    'spell_unnerfed_cone_of_cold',
    'spell_flamecannon',
    'spell_unnerfed_wrath',
    'spell_test_spellpower',
    'spell_flame_geyser',
    'spell_jade_lightning',
    'spell_imp-losion',
    'spell_axe_kick',
    'spell_dinner_time',
    'spell_test_choose_one',
    'spell_on_the_hunt',
    'spell_dark_possession',
    'spell_flanking_strike',
    'spell_falling_stones',
    'spell_armed_and_ready',
    'spell_hammer_of_wrath',
    'spell_fan_of_knives',
    'spell_zap_',
    'spell_whirlwind',
    'spell_living_trees_3',
    'spell_living_trees_1',
    'spell_serrated_shield',
    'spell_multiple_strike',
    'spell_crusader_strike',
    'spell_excavated_evil',
    'spell_razorpetal',
    'spell_pound',
    'spell_avenging_wrath',
    'spell_spike_toed_booterang',
    'spell_quartz_spellstone',
    'spell_fact_check',
    'spell_living_roots_1',
    'spell_living_roots_3',
    'spell_spirit_lash',
    'spell_thats_mine',
    'spell_blood_to_ichor',
    'spell_holy_nova',
    'spell_hot_shot',
    'spell_lunar_strike',
    'spell_ashes_to_ashes',
    'spell_firebloom_toxin',
    'spell_revenge',
    'spell_cinderstorm',
    'spell_multi-shot',
    'spell_lava_shock',
    'spell_greater_quartz_spellstone',
    'spell_clown_fiesta',
    'spell_frostfire_bolt',
    'spell_moonfire',
    'spell_feedback_loop',
    'spell_fiery_kitsune_punch',
    'spell_fist_of_jaraxxus',
    'spell_arcane_missiles',
    'spell_arcane_blast',
    'spell_cleanup',
    'spell_firelands_portal',
    'spell_blizzard',
    'spell_invocation_of_fire',
    'spell_jasper_spellstone',
    'spell_grievous_bite',
    'spell_unnerfed_soulfire',
    'spell_swipe',
    'spell_pocket_sand',
    'spell_shadowflame',
    'spell_windswept_strike',
    'spell_holy_smite',
    'spell_howling_blast',
    'spell_forbidden_flame',
    'spell_starfire',
    'spell_lesser_amethyst_spellstone',
    'spell_tsunami',
    'spell_death_and_decay',
    'spell_wing_blast',
    'spell_frost_strike',
    'spell_rebellious_flame',
    'spell_unnerfed_savagery',
    'spell_frostbolt',
    'spell_trojan_horse',
    'spell_starfall',
    'spell_ddos',
    'spell_cone_of_cold',
    'spell_focus_fire',
    'spell_dragon_roar',
    'spell_crackle',
    'spell_felfire_potion',
    'spell_wrath',
    'spell_unnerfed_headcrack',
    'spell_volcano',
    'spell_unnerfed_backstab',
    'spell_shiv',
    'spell_demonheart',
    'spell_bouncing_blade',
    'spell_greater_arcane_missiles',
    'spell_shield_slam',
    'spell_spirit_bomb',
    'spell_avalanche',
    'spell_amethyst_spellstone',
    'spell_lesser_quartz_spellstone',
    'spell_judgement_day',
    'spell_barrage',
    'spell_sinister_strike',
    'spell_frost_shock',
    'spell_tidal_surge',
    'spell_suction',
    'spell_pulse_bomb',
    'spell_devastate',
    'spell_earth_shock',
    'spell_bash',
    'spell_wanted',
    'spell_fireball',
    'spell_soulfire',
    'spell_powershot',
    'spell_jade_shuriken',
    'spell_heartstrike',
    'spell_explosive_shot',
    'spell_tail_swipe',
    'spell_shooting_star',
    'spell_hellfire',
    'spell_impending_doom',
    'spell_palm_strike',
    'spell_astroblast',
    'spell_ignite',
    'spell_beakered_lightning',
    'spell_lightning_storm',
    'spell_breath_of_sindragosa',
    'spell_feeding_time',
    'spell_eviscerate',
    'spell_bane_of_doom',
    'spell_obliterate',
    'spell_vampiric_touch',
    'spell_lava_burst',
    'spell_arcane_implosion',
    'spell_defile',
    'spell_ricochet_shot',
    'spell_night_bloom',
    'spell_mutagen',
    'spell_sunfire',
    'spell_sponsored_funding',
    'spell_mortal_strike',
    'spell_mutate',
    'spell_invocation_of_air',
    'spell_unnerfed_blizzard',
    'spell_unnerfed_starfall_3',
    'spell_unnerfed_starfall_2',
    'spell_unnerfed_starfall_1',
    'spell_rising_sun_kick',
    'spell_unnerfed_wrath_2',
    'spell_unnerfed_wrath_3',
    'spell_starfall_3',
    'spell_starfall_1',
    'spell_starfall_2',
    'spell_inner_rage',
    'spell_unnerfed_wrath_1',
    'spell_ashes_of_the_vale',
    'spell_pyroblast',
    'spell_solar_flare',
    'spell_blade_flurry',
    'spell_temporal_flux',
    'spell_warpath',
    'spell_unearth',
    'spell_drain_life',
    'spell_shadow_bolt',
    'spell_scorch',
    'spell_bear_hug',
    'spell_savagery',
    'spell_flamestrike',
    'spell_unnerfed_shiv',
    'spell_ysera_awakens',
    'spell_unnerfed_starfall',
    'spell_meteor_storm',
    'spell_kill_command',
    'spell_drain_soul',
    'spell_unexpected_results',
    'spell_consecration',
    'spell_greater_jasper_spellstone',
    'spell_mind_blast',
    'spell_reckless_flurry',
    'spell_stormcrack',
    'spell_cleave',
    'spell_shadow_strike',
    'spell_crusade',
    'spell_demonwrath',
    'spell_lightbomb',
    'spell_bomb_toss',
    'spell_darkbomb',
    'spell_doomerang',
    'spell_set_ablaze',
    'spell_flame_lance',
    'spell_demonbolt',
    'spell_arcane_shot',
    'spell_arcane_explosion',
    'spell_ultimate_infestation',
    'spell_payload',
    'spell_glacial_spike',
    'spell_volcanic_potion',
    'spell_molten_skin',
    'spell_mortal_coil',
    'spell_cobra_shot',
    'spell_nerd_rage',
    'spell_headcrack',
    'spell_earthquake',
    'spell_balance',
    'spell_crushing_hand',
    'spell_plasma_blast',
    'spell_aoe_spawn',
    'spell_temporal_anomaly',
    'spell_cheap_shot',
    'spell_spreading_madness',
    'spell_unnerfed_blade_flurry',
    'spell_triple_shot',
    'spell_holy_water',
    'spell_slam',
    'spell_chaos_bolt',
    'spell_forked_lightning',
    'spell_appetizer_3',
    'spell_appetizer_1',
    'spell_timepiece_of_horror',
    'spell_dragons_breath',
    'spell_elemental_destruction',
    'spell_meteor',
    'spell_beneath_the_waters',
    'spell_demonfire',
    'spell_wrath_1',
    'spell_wrath_2',
    'spell_wrath_3',
    'spell_dragonfire_potion',
    'spell_bsod',
    'spell_blood_boil',
    'spell_toxic_arrow',
    'spell_nerf',
    'spell_greater_amethyst_spellstone',
]


def main():
    cards = frozenset(CARDS)
    for (card, filepath) in iter_card_and_file_path():
        card_id = os.path.basename(filepath).replace('.json', '')
        if card_id not in cards:
            continue
        description = card['description']
        if description == '':
            continue

        def replacer(match):
            deals_string = match.group(1) + 'eal $' + match.group(2)
            if len(match.groups()) == 4:
                deals_string += '-$' + match.group(3)
            return deals_string

        # Deal with deal or deals
        description = re.sub(pattern=r'([Dd])eal (\d+)-?(\d+)?', string=description, repl=replacer)
        card['description'] = description
        write_card(card, filepath)
        print('%s: %s' % (card_id, description))


if __name__ == '__main__':
    main()
