fragment entity on Entity {
  id
  name
  description
  cardId
  cardType
  entityType
  rarity
  location {
    index
    zone
    player
  }
  owner
  boardPosition
  attack
  baseAttack
  hp
  baseHp
  maxHp
  armor
  manaCost
  baseManaCost
  durability
  spellDamage
  overload
  extraAttack
  mana
  maxMana
  lockedMana
  battlecry
  cannotAttack
  charge
  chooseOne
  collectible
  combo
  conditionMet
  deathrattles
  deflect
  destroyed
  discarded
  divineShield
  enraged
  frozen
  gameStarted
  gold
  hostsTrigger
  immune
  isStartingTurn
  lifesteal
  permanent
  playable
  poisonous
  roasted
  rush
  silenced
  stealth
  summoningSickness
  taunt
  uncensored
  underAura
  untargetableBySpells
  windfury
  charges
  countUntilCast
  fires
  host
  heroClasses
  cardSet
  cardSets
  enchantmentType
  tribes
  tooltips {
    text
    keywords
  }
  note
}
