fragment entity on Entity {
  ...entitySummary
  location {
    ...entityLocation
  }
  boardPosition
  baseAttack
  baseHp
  baseManaCost
  durability
  spellDamage
  overload
  extraAttack
  mana
  maxMana
  lockedMana
  cannotAttack
  chooseOne
  combo
  conditionMet
  deflect
  destroyed
  discarded
  enraged
  frozen
  gameStarted
  gold
  hostsTrigger
  immune
  isStartingTurn
  permanent
  roasted
  silenced
  summoningSickness
  uncensored
  underAura
  untargetableBySpells
  charges
  countUntilCast
  fires
  host
  cardSet
  cardSets
  enchantmentType
  tooltips {
    text
    keywords
  }
  note
}
