/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IAuthenticatorConfigEntry;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthenticatorConfigEntry implements VertxPojo, IAuthenticatorConfigEntry {

    private static final long serialVersionUID = 1L;

    private String authenticatorId;
    private String value;
    private String name;

    public AuthenticatorConfigEntry() {}

    public AuthenticatorConfigEntry(IAuthenticatorConfigEntry value) {
        this.authenticatorId = value.getAuthenticatorId();
        this.value = value.getValue();
        this.name = value.getName();
    }

    public AuthenticatorConfigEntry(
        String authenticatorId,
        String value,
        String name
    ) {
        this.authenticatorId = authenticatorId;
        this.value = value;
        this.name = name;
    }

        public AuthenticatorConfigEntry(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for
     * <code>keycloak.authenticator_config_entry.authenticator_id</code>.
     */
    @Override
    public String getAuthenticatorId() {
        return this.authenticatorId;
    }

    /**
     * Setter for
     * <code>keycloak.authenticator_config_entry.authenticator_id</code>.
     */
    @Override
    public AuthenticatorConfigEntry setAuthenticatorId(String authenticatorId) {
        this.authenticatorId = authenticatorId;
        return this;
    }

    /**
     * Getter for <code>keycloak.authenticator_config_entry.value</code>.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>keycloak.authenticator_config_entry.value</code>.
     */
    @Override
    public AuthenticatorConfigEntry setValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Getter for <code>keycloak.authenticator_config_entry.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>keycloak.authenticator_config_entry.name</code>.
     */
    @Override
    public AuthenticatorConfigEntry setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AuthenticatorConfigEntry other = (AuthenticatorConfigEntry) obj;
        if (this.authenticatorId == null) {
            if (other.authenticatorId != null)
                return false;
        }
        else if (!this.authenticatorId.equals(other.authenticatorId))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.authenticatorId == null) ? 0 : this.authenticatorId.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthenticatorConfigEntry (");

        sb.append(authenticatorId);
        sb.append(", ").append(value);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IAuthenticatorConfigEntry from) {
        setAuthenticatorId(from.getAuthenticatorId());
        setValue(from.getValue());
        setName(from.getName());
    }

    @Override
    public <E extends IAuthenticatorConfigEntry> E into(E into) {
        into.from(this);
        return into;
    }
}
