/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IClientAttributes;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClientAttributes implements VertxPojo, IClientAttributes {

    private static final long serialVersionUID = 1L;

    private String clientId;
    private String name;
    private String value;

    public ClientAttributes() {}

    public ClientAttributes(IClientAttributes value) {
        this.clientId = value.getClientId();
        this.name = value.getName();
        this.value = value.getValue();
    }

    public ClientAttributes(
        String clientId,
        String name,
        String value
    ) {
        this.clientId = clientId;
        this.name = name;
        this.value = value;
    }

        public ClientAttributes(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>keycloak.client_attributes.client_id</code>.
     */
    @Override
    public String getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>keycloak.client_attributes.client_id</code>.
     */
    @Override
    public ClientAttributes setClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * Getter for <code>keycloak.client_attributes.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>keycloak.client_attributes.name</code>.
     */
    @Override
    public ClientAttributes setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>keycloak.client_attributes.value</code>.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>keycloak.client_attributes.value</code>.
     */
    @Override
    public ClientAttributes setValue(String value) {
        this.value = value;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ClientAttributes other = (ClientAttributes) obj;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClientAttributes (");

        sb.append(clientId);
        sb.append(", ").append(name);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IClientAttributes from) {
        setClientId(from.getClientId());
        setName(from.getName());
        setValue(from.getValue());
    }

    @Override
    public <E extends IClientAttributes> E into(E into) {
        into.from(this);
        return into;
    }
}
