/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IFedUserRequiredAction;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FedUserRequiredAction implements VertxPojo, IFedUserRequiredAction {

    private static final long serialVersionUID = 1L;

    private String requiredAction;
    private String userId;
    private String realmId;
    private String storageProviderId;

    public FedUserRequiredAction() {}

    public FedUserRequiredAction(IFedUserRequiredAction value) {
        this.requiredAction = value.getRequiredAction();
        this.userId = value.getUserId();
        this.realmId = value.getRealmId();
        this.storageProviderId = value.getStorageProviderId();
    }

    public FedUserRequiredAction(
        String requiredAction,
        String userId,
        String realmId,
        String storageProviderId
    ) {
        this.requiredAction = requiredAction;
        this.userId = userId;
        this.realmId = realmId;
        this.storageProviderId = storageProviderId;
    }

        public FedUserRequiredAction(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for
     * <code>keycloak.fed_user_required_action.required_action</code>.
     */
    @Override
    public String getRequiredAction() {
        return this.requiredAction;
    }

    /**
     * Setter for
     * <code>keycloak.fed_user_required_action.required_action</code>.
     */
    @Override
    public FedUserRequiredAction setRequiredAction(String requiredAction) {
        this.requiredAction = requiredAction;
        return this;
    }

    /**
     * Getter for <code>keycloak.fed_user_required_action.user_id</code>.
     */
    @Override
    public String getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>keycloak.fed_user_required_action.user_id</code>.
     */
    @Override
    public FedUserRequiredAction setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>keycloak.fed_user_required_action.realm_id</code>.
     */
    @Override
    public String getRealmId() {
        return this.realmId;
    }

    /**
     * Setter for <code>keycloak.fed_user_required_action.realm_id</code>.
     */
    @Override
    public FedUserRequiredAction setRealmId(String realmId) {
        this.realmId = realmId;
        return this;
    }

    /**
     * Getter for
     * <code>keycloak.fed_user_required_action.storage_provider_id</code>.
     */
    @Override
    public String getStorageProviderId() {
        return this.storageProviderId;
    }

    /**
     * Setter for
     * <code>keycloak.fed_user_required_action.storage_provider_id</code>.
     */
    @Override
    public FedUserRequiredAction setStorageProviderId(String storageProviderId) {
        this.storageProviderId = storageProviderId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FedUserRequiredAction other = (FedUserRequiredAction) obj;
        if (this.requiredAction == null) {
            if (other.requiredAction != null)
                return false;
        }
        else if (!this.requiredAction.equals(other.requiredAction))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.realmId == null) {
            if (other.realmId != null)
                return false;
        }
        else if (!this.realmId.equals(other.realmId))
            return false;
        if (this.storageProviderId == null) {
            if (other.storageProviderId != null)
                return false;
        }
        else if (!this.storageProviderId.equals(other.storageProviderId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.requiredAction == null) ? 0 : this.requiredAction.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.realmId == null) ? 0 : this.realmId.hashCode());
        result = prime * result + ((this.storageProviderId == null) ? 0 : this.storageProviderId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FedUserRequiredAction (");

        sb.append(requiredAction);
        sb.append(", ").append(userId);
        sb.append(", ").append(realmId);
        sb.append(", ").append(storageProviderId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IFedUserRequiredAction from) {
        setRequiredAction(from.getRequiredAction());
        setUserId(from.getUserId());
        setRealmId(from.getRealmId());
        setStorageProviderId(from.getStorageProviderId());
    }

    @Override
    public <E extends IFedUserRequiredAction> E into(E into) {
        into.from(this);
        return into;
    }
}
