/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IIdpMapperConfig;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdpMapperConfig implements VertxPojo, IIdpMapperConfig {

    private static final long serialVersionUID = 1L;

    private String idpMapperId;
    private String value;
    private String name;

    public IdpMapperConfig() {}

    public IdpMapperConfig(IIdpMapperConfig value) {
        this.idpMapperId = value.getIdpMapperId();
        this.value = value.getValue();
        this.name = value.getName();
    }

    public IdpMapperConfig(
        String idpMapperId,
        String value,
        String name
    ) {
        this.idpMapperId = idpMapperId;
        this.value = value;
        this.name = name;
    }

        public IdpMapperConfig(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>keycloak.idp_mapper_config.idp_mapper_id</code>.
     */
    @Override
    public String getIdpMapperId() {
        return this.idpMapperId;
    }

    /**
     * Setter for <code>keycloak.idp_mapper_config.idp_mapper_id</code>.
     */
    @Override
    public IdpMapperConfig setIdpMapperId(String idpMapperId) {
        this.idpMapperId = idpMapperId;
        return this;
    }

    /**
     * Getter for <code>keycloak.idp_mapper_config.value</code>.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>keycloak.idp_mapper_config.value</code>.
     */
    @Override
    public IdpMapperConfig setValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Getter for <code>keycloak.idp_mapper_config.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>keycloak.idp_mapper_config.name</code>.
     */
    @Override
    public IdpMapperConfig setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IdpMapperConfig (");

        sb.append(idpMapperId);
        sb.append(", ").append(value);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IIdpMapperConfig from) {
        setIdpMapperId(from.getIdpMapperId());
        setValue(from.getValue());
        setName(from.getName());
    }

    @Override
    public <E extends IIdpMapperConfig> E into(E into) {
        into.from(this);
        return into;
    }
}
