/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IRedirectUris;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedirectUris implements VertxPojo, IRedirectUris {

    private static final long serialVersionUID = 1L;

    private String clientId;
    private String value;

    public RedirectUris() {}

    public RedirectUris(IRedirectUris value) {
        this.clientId = value.getClientId();
        this.value = value.getValue();
    }

    public RedirectUris(
        String clientId,
        String value
    ) {
        this.clientId = clientId;
        this.value = value;
    }

        public RedirectUris(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>keycloak.redirect_uris.client_id</code>.
     */
    @Override
    public String getClientId() {
        return this.clientId;
    }

    /**
     * Setter for <code>keycloak.redirect_uris.client_id</code>.
     */
    @Override
    public RedirectUris setClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * Getter for <code>keycloak.redirect_uris.value</code>.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>keycloak.redirect_uris.value</code>.
     */
    @Override
    public RedirectUris setValue(String value) {
        this.value = value;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RedirectUris other = (RedirectUris) obj;
        if (this.clientId == null) {
            if (other.clientId != null)
                return false;
        }
        else if (!this.clientId.equals(other.clientId))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.clientId == null) ? 0 : this.clientId.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RedirectUris (");

        sb.append(clientId);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRedirectUris from) {
        setClientId(from.getClientId());
        setValue(from.getValue());
    }

    @Override
    public <E extends IRedirectUris> E into(E into) {
        into.from(this);
        return into;
    }
}
