/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.pojos;


import com.hiddenswitch.framework.schema.keycloak.tables.interfaces.IRequiredActionConfig;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequiredActionConfig implements VertxPojo, IRequiredActionConfig {

    private static final long serialVersionUID = 1L;

    private String requiredActionId;
    private String value;
    private String name;

    public RequiredActionConfig() {}

    public RequiredActionConfig(IRequiredActionConfig value) {
        this.requiredActionId = value.getRequiredActionId();
        this.value = value.getValue();
        this.name = value.getName();
    }

    public RequiredActionConfig(
        String requiredActionId,
        String value,
        String name
    ) {
        this.requiredActionId = requiredActionId;
        this.value = value;
        this.name = name;
    }

        public RequiredActionConfig(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for
     * <code>keycloak.required_action_config.required_action_id</code>.
     */
    @Override
    public String getRequiredActionId() {
        return this.requiredActionId;
    }

    /**
     * Setter for
     * <code>keycloak.required_action_config.required_action_id</code>.
     */
    @Override
    public RequiredActionConfig setRequiredActionId(String requiredActionId) {
        this.requiredActionId = requiredActionId;
        return this;
    }

    /**
     * Getter for <code>keycloak.required_action_config.value</code>.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>keycloak.required_action_config.value</code>.
     */
    @Override
    public RequiredActionConfig setValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Getter for <code>keycloak.required_action_config.name</code>.
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>keycloak.required_action_config.name</code>.
     */
    @Override
    public RequiredActionConfig setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RequiredActionConfig (");

        sb.append(requiredActionId);
        sb.append(", ").append(value);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRequiredActionConfig from) {
        setRequiredActionId(from.getRequiredActionId());
        setValue(from.getValue());
        setName(from.getName());
    }

    @Override
    public <E extends IRequiredActionConfig> E into(E into) {
        into.from(this);
        return into;
    }
}
