/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.spellsource;


import com.hiddenswitch.framework.schema.spellsource.tables.Cards;
import com.hiddenswitch.framework.schema.spellsource.tables.CardsInDeck;
import com.hiddenswitch.framework.schema.spellsource.tables.DeckPlayerAttributeTuples;
import com.hiddenswitch.framework.schema.spellsource.tables.DeckShares;
import com.hiddenswitch.framework.schema.spellsource.tables.Decks;


/**
 * Convenience access to all tables in spellsource
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>spellsource.cards</code>.
     */
    public static final Cards CARDS = Cards.CARDS;

    /**
     * The table <code>spellsource.cards_in_deck</code>.
     */
    public static final CardsInDeck CARDS_IN_DECK = CardsInDeck.CARDS_IN_DECK;

    /**
     * The table <code>spellsource.deck_player_attribute_tuples</code>.
     */
    public static final DeckPlayerAttributeTuples DECK_PLAYER_ATTRIBUTE_TUPLES = DeckPlayerAttributeTuples.DECK_PLAYER_ATTRIBUTE_TUPLES;

    /**
     * indicates a deck shared to a player
     */
    public static final DeckShares DECK_SHARES = DeckShares.DECK_SHARES;

    /**
     * The table <code>spellsource.decks</code>.
     */
    public static final Decks DECKS = Decks.DECKS;
}
