plugins {
  id 'java-library'
  id 'com.google.protobuf' version '0.9.4'
}

configurations {
  protocPlugin
}

dependencies {
  implementation project(':vertx-grpc:vertx-grpc-client')
  implementation project(':vertx-grpc:vertx-grpc-server')

  protocPlugin project(path: ':vertx-grpc:vertx-grpc-protoc-plugin2', configuration: 'shadow')

}


test {
  dependsOn "generateProto"
}

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:$protocVersion"
  }
  plugins {
    grpc {
      artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
    }
    vertx {
      path = tasks.getByPath(':vertx-grpc:vertx-grpc-protoc-plugin2:shadowJar').archiveFile.get().asFile
    }
  }
  generateProtoTasks {
    all().each { task ->
      task.plugins {
        grpc {}
        vertx {}
      }
      task.dependsOn ':vertx-grpc:vertx-grpc-protoc-plugin2:shadowJar'
    }
  }
}
