/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.LocalDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IDatabasechangeloglock extends VertxPojo, Serializable {

    /**
     * Setter for <code>keycloak.databasechangeloglock.id</code>.
     */
    public IDatabasechangeloglock setId(Integer value);

    /**
     * Getter for <code>keycloak.databasechangeloglock.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>keycloak.databasechangeloglock.locked</code>.
     */
    public IDatabasechangeloglock setLocked(Boolean value);

    /**
     * Getter for <code>keycloak.databasechangeloglock.locked</code>.
     */
    public Boolean getLocked();

    /**
     * Setter for <code>keycloak.databasechangeloglock.lockgranted</code>.
     */
    public IDatabasechangeloglock setLockgranted(LocalDateTime value);

    /**
     * Getter for <code>keycloak.databasechangeloglock.lockgranted</code>.
     */
    public LocalDateTime getLockgranted();

    /**
     * Setter for <code>keycloak.databasechangeloglock.lockedby</code>.
     */
    public IDatabasechangeloglock setLockedby(String value);

    /**
     * Getter for <code>keycloak.databasechangeloglock.lockedby</code>.
     */
    public String getLockedby();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IDatabasechangeloglock
     */
    public void from(IDatabasechangeloglock from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IDatabasechangeloglock
     */
    public <E extends IDatabasechangeloglock> E into(E into);

        @Override
        public default IDatabasechangeloglock fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getInteger,"id","java.lang.Integer");
                setOrThrow(this::setLocked,json::getBoolean,"locked","java.lang.Boolean");
                setOrThrow(this::setLockgranted,key -> {String s = json.getString(key); return s==null?null:java.time.LocalDateTime.parse(s);},"lockgranted","java.time.LocalDateTime");
                setOrThrow(this::setLockedby,json::getString,"lockedby","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("locked",getLocked());
                json.put("lockgranted",getLockgranted()==null?null:getLockgranted().toString());
                json.put("lockedby",getLockedby());
                return json;
        }

}
