/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFedUserGroupMembership extends VertxPojo, Serializable {

    /**
     * Setter for <code>keycloak.fed_user_group_membership.group_id</code>.
     */
    public IFedUserGroupMembership setGroupId(String value);

    /**
     * Getter for <code>keycloak.fed_user_group_membership.group_id</code>.
     */
    public String getGroupId();

    /**
     * Setter for <code>keycloak.fed_user_group_membership.user_id</code>.
     */
    public IFedUserGroupMembership setUserId(String value);

    /**
     * Getter for <code>keycloak.fed_user_group_membership.user_id</code>.
     */
    public String getUserId();

    /**
     * Setter for <code>keycloak.fed_user_group_membership.realm_id</code>.
     */
    public IFedUserGroupMembership setRealmId(String value);

    /**
     * Getter for <code>keycloak.fed_user_group_membership.realm_id</code>.
     */
    public String getRealmId();

    /**
     * Setter for
     * <code>keycloak.fed_user_group_membership.storage_provider_id</code>.
     */
    public IFedUserGroupMembership setStorageProviderId(String value);

    /**
     * Getter for
     * <code>keycloak.fed_user_group_membership.storage_provider_id</code>.
     */
    public String getStorageProviderId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IFedUserGroupMembership
     */
    public void from(IFedUserGroupMembership from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IFedUserGroupMembership
     */
    public <E extends IFedUserGroupMembership> E into(E into);

        @Override
        public default IFedUserGroupMembership fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setGroupId,json::getString,"group_id","java.lang.String");
                setOrThrow(this::setUserId,json::getString,"user_id","java.lang.String");
                setOrThrow(this::setRealmId,json::getString,"realm_id","java.lang.String");
                setOrThrow(this::setStorageProviderId,json::getString,"storage_provider_id","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("group_id",getGroupId());
                json.put("user_id",getUserId());
                json.put("realm_id",getRealmId());
                json.put("storage_provider_id",getStorageProviderId());
                return json;
        }

}
