/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProtocolMapperConfig extends VertxPojo, Serializable {

    /**
     * Setter for
     * <code>keycloak.protocol_mapper_config.protocol_mapper_id</code>.
     */
    public IProtocolMapperConfig setProtocolMapperId(String value);

    /**
     * Getter for
     * <code>keycloak.protocol_mapper_config.protocol_mapper_id</code>.
     */
    public String getProtocolMapperId();

    /**
     * Setter for <code>keycloak.protocol_mapper_config.value</code>.
     */
    public IProtocolMapperConfig setValue(String value);

    /**
     * Getter for <code>keycloak.protocol_mapper_config.value</code>.
     */
    public String getValue();

    /**
     * Setter for <code>keycloak.protocol_mapper_config.name</code>.
     */
    public IProtocolMapperConfig setName(String value);

    /**
     * Getter for <code>keycloak.protocol_mapper_config.name</code>.
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IProtocolMapperConfig
     */
    public void from(IProtocolMapperConfig from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IProtocolMapperConfig
     */
    public <E extends IProtocolMapperConfig> E into(E into);

        @Override
        public default IProtocolMapperConfig fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setProtocolMapperId,json::getString,"protocol_mapper_id","java.lang.String");
                setOrThrow(this::setValue,json::getString,"value","java.lang.String");
                setOrThrow(this::setName,json::getString,"name","java.lang.String");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("protocol_mapper_id",getProtocolMapperId());
                json.put("value",getValue());
                json.put("name",getName());
                return json;
        }

}
