/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.keycloak.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IResourceServerResource extends VertxPojo, Serializable {

    /**
     * Setter for <code>keycloak.resource_server_resource.id</code>.
     */
    public IResourceServerResource setId(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>keycloak.resource_server_resource.name</code>.
     */
    public IResourceServerResource setName(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>keycloak.resource_server_resource.type</code>.
     */
    public IResourceServerResource setType(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.type</code>.
     */
    public String getType();

    /**
     * Setter for <code>keycloak.resource_server_resource.icon_uri</code>.
     */
    public IResourceServerResource setIconUri(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.icon_uri</code>.
     */
    public String getIconUri();

    /**
     * Setter for <code>keycloak.resource_server_resource.owner</code>.
     */
    public IResourceServerResource setOwner(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.owner</code>.
     */
    public String getOwner();

    /**
     * Setter for <code>keycloak.resource_server_resource.resource_server_id</code>.
     */
    public IResourceServerResource setResourceServerId(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.resource_server_id</code>.
     */
    public String getResourceServerId();

    /**
     * Setter for <code>keycloak.resource_server_resource.owner_managed_access</code>.
     */
    public IResourceServerResource setOwnerManagedAccess(Boolean value);

    /**
     * Getter for <code>keycloak.resource_server_resource.owner_managed_access</code>.
     */
    public Boolean getOwnerManagedAccess();

    /**
     * Setter for <code>keycloak.resource_server_resource.display_name</code>.
     */
    public IResourceServerResource setDisplayName(String value);

    /**
     * Getter for <code>keycloak.resource_server_resource.display_name</code>.
     */
    public String getDisplayName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IResourceServerResource
     */
    public void from(IResourceServerResource from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IResourceServerResource
     */
    public <E extends IResourceServerResource> E into(E into);

    @Override
    public default IResourceServerResource fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setId(json.getString("id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("id","java.lang.String",e);
        }
        try {
            setName(json.getString("name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("name","java.lang.String",e);
        }
        try {
            setType(json.getString("type"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("type","java.lang.String",e);
        }
        try {
            setIconUri(json.getString("icon_uri"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("icon_uri","java.lang.String",e);
        }
        try {
            setOwner(json.getString("owner"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("owner","java.lang.String",e);
        }
        try {
            setResourceServerId(json.getString("resource_server_id"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("resource_server_id","java.lang.String",e);
        }
        try {
            setOwnerManagedAccess(json.getBoolean("owner_managed_access"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("owner_managed_access","java.lang.Boolean",e);
        }
        try {
            setDisplayName(json.getString("display_name"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("display_name","java.lang.String",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("name",getName());
        json.put("type",getType());
        json.put("icon_uri",getIconUri());
        json.put("owner",getOwner());
        json.put("resource_server_id",getResourceServerId());
        json.put("owner_managed_access",getOwnerManagedAccess());
        json.put("display_name",getDisplayName());
        return json;
    }

}
