package net.demilich.metastone.game.cards.desc;

public enum CardDescArg {
	NAME, DESCRIPTION, LEGACY, TYPE, HERO_CLASS, HERO_CLASSES, RARITY, SET, BASE_MANA_COST, COLLECTIBLE, ATTRIBUTES, MANA_COST_MODIFIER, BATTLECRY, DEATHRATTLE, TRIGGERS, AURAS, BASE_ATTACK, BASE_HP, TARGET_SELECTION, SPELL, CONDITION, ID, PASSIVE_TRIGGERS, GAME_TRIGGERS, DECK_TRIGGERS;
}
