/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.spellsource.enums;


import com.hiddenswitch.framework.schema.spellsource.Spellsource;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum GameUserVictoryEnum implements EnumType {

    UNKNOWN("UNKNOWN"),

    WON("WON"),

    LOST("LOST"),

    DISCONNECTED("DISCONNECTED"),

    CONCEDED("CONCEDED");

    private final String literal;

    private GameUserVictoryEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Spellsource.SPELLSOURCE;
    }

    @Override
    public String getName() {
        return "game_user_victory_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static GameUserVictoryEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(GameUserVictoryEnum.class, literal);
    }
}
