/*
 * This file is generated by jOOQ.
 */
package com.hiddenswitch.framework.schema.spellsource.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.time.OffsetDateTime;


import static io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo.*;
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFriends extends VertxPojo, Serializable {

    /**
     * Setter for <code>spellsource.friends.id</code>.
     */
    public IFriends setId(String value);

    /**
     * Getter for <code>spellsource.friends.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>spellsource.friends.friend</code>.
     */
    public IFriends setFriend(String value);

    /**
     * Getter for <code>spellsource.friends.friend</code>.
     */
    public String getFriend();

    /**
     * Setter for <code>spellsource.friends.created_at</code>.
     */
    public IFriends setCreatedAt(OffsetDateTime value);

    /**
     * Getter for <code>spellsource.friends.created_at</code>.
     */
    public OffsetDateTime getCreatedAt();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IFriends
     */
    public void from(IFriends from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IFriends
     */
    public <E extends IFriends> E into(E into);

        @Override
        public default IFriends fromJson(io.vertx.core.json.JsonObject json) {
                setOrThrow(this::setId,json::getString,"id","java.lang.String");
                setOrThrow(this::setFriend,json::getString,"friend","java.lang.String");
                setOrThrow(this::setCreatedAt,key -> {String s = json.getString(key); return s==null?null:java.time.OffsetDateTime.parse(s);},"created_at","java.time.OffsetDateTime");
                return this;
        }


        @Override
        public default io.vertx.core.json.JsonObject toJson() {
                io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
                json.put("id",getId());
                json.put("friend",getFriend());
                json.put("created_at",getCreatedAt()==null?null:getCreatedAt().toString());
                return json;
        }

}
