package net.demilich.metastone.game.spells.desc.aura;

public enum AuraArg {
	CLASS,
	FILTER,
	TARGET,
	SECONDARY_TARGET,
	ATTRIBUTE,
	VALUE,
	ATTACK_BONUS,
	HP_BONUS,
	APPLY_EFFECT,
	PAY_EFFECT,
	@Deprecated(since = "2")
	SECONDARY_TRIGGER,
	TRIGGERS,
	@Deprecated(since = "2")
	ALWAYS_APPLY,
	REVERT_TRIGGER,
	SPELL_CONDITION,
	CONDITION,
	CARD,
	RACES,
	CAN_AFFORD_CONDITION,
	AMOUNT_OF_CURRENCY,
	TARGET_SELECTION,
	CHOOSE_ONE_OVERRIDE,
	PERSISTENT_OWNER,
	SECONDARY_FILTER,
	REMOVE_EFFECT,
	DESCRIPTION,
	NAME,
	SPELL,
	ZONES
}
