name: Build Image (Develop)
on:
  push:
    branches: ['develop']
  
jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true # TODO still needed just for website?
      - run: git lfs checkout 
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: gradle/wrapper-validation-action@v1
        # TODO run website tests
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Website Image
        run: ./gradlew spellsource-web:githubDockerPush