name: Build Image
on:
  push:
    branches: ['develop']
    tags: ['*']

jobs:
  build-and-deploy-server:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs checkout
      - name: Checkout public submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init vertx-jooq-fork
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: temurin
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Test with Gradle
        run: ./gradlew --no-parallel test
      - name: Build and push server image
        run: ./gradlew spellsource-server:githubDockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy-website:
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs checkout
      - name: Checkout public submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init vertx-jooq-fork
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: temurin
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set Project Version
        run: |
          COMMIT_SHA=$(git rev-parse --short=7 HEAD)
          TIMESTAMP=$(date +%s)
          echo "PROJECT_VERSION=${COMMIT_SHA}-${TIMESTAMP}" >> $GITHUB_ENV
      - name: Build and push website image
        run: ./gradlew spellsource-web:githubDockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_VERSION: ${{ env.PROJECT_VERSION }}
