name: Tests
on:
  push: { }
  pull_request: { }
jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    container: "ubuntu:22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs checkout
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: oracle
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x.x
      - uses: gradle/wrapper-validation-action@v1
      - name: Test with Gradle
        run: ./gradlew --no-parallel test
