name: Tests
on:
  push: { }
  pull_request: { }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
      - run: git lfs checkout
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: temurin
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: gradle/actions/wrapper-validation@v3
      - name: Test with Gradle
        run: ./gradlew --no-parallel test
