name: Build Server
on:
  push:
    branches: ['develop']
    tags: ['*']

jobs:
  test-and-deploy-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: git lfs checkout
      - name: Checkout public submodules
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init vertx-jooq-fork spellsource-ts-proto/ts-proto
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: temurin
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Run server tests
        run: ./gradlew --no-parallel spellsource-server:test
      - name: Build and push server image
        run: ./gradlew spellsource-server:githubDockerPush
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
