package net.demilich.metastone.game.spells;

public enum PlayerAttribute {
	MANA,
	MAX_MANA,
	HAND_COUNT,
	HERO_POWER_USED,
	DECK_COUNT,
	LAST_MANA_COST,
	SECRET_COUNT,
	SPELLS_CAST,
	OVERLOADED_THIS_GAME,
	CARDS_DISCARDED,
	DAMAGE_THIS_TURN
}
